language: python
python:
    - "3.2"
    - "3.3"
# command to install dependencies
install:
    - "pip install pylint --use-mirrors"
    - "pip install coverage --use-mirrors"
# command to run tests
script: 
    - nosetests --with-coverage
    - pylint --rcfile=pylint.conf fitg
